#!/bin/bash
#
#!/usr/bin/env -S awk -f ${_} -- <= -S non POSIX
# coding: utf-8
#
# Program for showing the hierarchy of specific processes on a Unix computer.
# Like pstree but with searching for specific processes with pgrep first and display
# hierarchy of matching processes (parents and children)
# should work on any Unix supporting commands :
# pgrep
# ps (ax|-e) -o pid=,ppid=,user=,comm=|ucomm=,stime=|start=,args=
# (RedHat/CentOS/Fedora/Ubuntu/Suse/Solaris...)
#

# __author__ = "Franck Jouvanceau"
# __copyright__ = "Copyright 2020, Franck Jouvanceau"
# __license__ = "MIT"

usage() {
    cat - <<'EOF'
    usage: pgtree [-W] [-RIya] [-C <when>] [-O <psfield>] [-c|-k|-K] [-1|-p <pid1>,...|<pgrep args>]

    -I : use -o uid instead of -o user for ps command
         (if uid/user mapping is broken ps command can be stuck)
    -c : display processes and children only
    -k : kill -TERM processes and children
    -K : kill -KILL processes and children
    -y : do not ask for confirmation to kill
    -R : force use of internal pgrep
    -C : color preference : y/yes/always or n/no/never (default auto)
    -w : tty wrap text : y/yes or n/no (default y)
    -W : watch and follow process tree every 2s
    -a : use ascii characters
    -T : display threads (ps must support -T option)
    -O <psfield>[,psfield,...] : display multiple <psfield> instead of 'stime' in output
                   <psfield> must be valid with ps -o <psfield> command

    by default display full process hierarchy (parents + children of selected processes)

    -p <pids> : select processes pids to display hierarchy (default 0)
    -1 : display hierachy children of pid 1 (not including pid 0)
    <pgrep args> : use pgrep to select processes (see pgrep -h)

    found pids are prefixed with ►
EOF
    exit 1
}

PGT_PGREP=$(type -p pgrep)
[ "$PGT_PGREP" ] || PGT_PGREP='_pgrep'
ps -p $$ -o ucomm >/dev/null 2>&1 && PGT_COMM=ucomm
[ ! "$PGT_COMM" ] && ps -p $$ -o comm >/dev/null 2>&1 && PGT_COMM=comm
[ "$PGT_COMM" ] && {
    ps -p $$ -o stime >/dev/null 2>&1 && PGT_STIME=stime
    [ ! "$PGT_STIME" ] && ps -p $$ -o start >/dev/null 2>&1 && PGT_STIME=start
    [ ! "$PGT_STIME" ] && PGT_STIME=time
}
# busybox no -p option
[ ! "$PGT_COMM" ] && ! ps -p $$ >/dev/null 2>&1 && PGT_COMM=comm && PGT_STIME=time

SYSTEM=$(uname -s 2>/dev/null || echo "Linux")
PS_OPTION="ax"
case "$SYSTEM" in
    AIX)    PS_OPTION="-e"; PGT_STIME="start" ;;
    Darwin) PGT_STIME="start" ;;
    SunOS)  PS_OPTION="-e"; PGT_COMM="fname" ;;
esac

[ -x /bin/nawk ] && awk=nawk || awk=awk
pgtreeawk=$(cat <<'EOF'
function runcmd(cmd) {
    # run command
    RS = "\003"    # Record Separator to EOT
    $0 = ""        # if cmd has no output
    cmd | getline
    close(cmd)
    RS="\n"
    sub("\n$", "")  # Remove last \n
    return $0
}

function ask(prompt) {
    # input text
    printf("%s", prompt)
    getline answer < "-"
    return answer
}

function treedisplay(use_ascii, use_color) {
    # Tree display attributes
    if (use_ascii) {
        selected = ">"
        child = "|_"
        notchild = "| "
        lastchild = "\\_"
    } else {
        selected = "►"
        child = "├─"
        notchild = "│ "
        lastchild = "└─"
    }
    if (use_color) {
        COLOR_FG = "\x1b[38;5;"
        COLOR_RESET = "\x1b[0m"
        colors["pid"] = "12m"
        colors["user"] = "11m"
        colors["uid"] = "11m"
        colors["comm"] = "10m"
        colors["ucomm"] = "10m"
        colors["fname"] = "10m"
        colors["stime"] = "14m"
        colors["start"] = "14m"
        colors["args"] = "15m"
        colors["default"] = "13m"
    }
}

function colorize(field, value) {
    # colorize fields
    if (field in colors)
        return COLOR_FG colors[field] value COLOR_RESET
    return COLOR_FG colors["default"] value
}

function proctree(pids, use_ascii, use_color) {
    # Manage process tree of pids
    for (i in pids)
        all_pids[pids[i]]=1
    treedisplay(use_ascii, use_color)
    get_psinfo()
    build_tree()
}
function strip(str) {
    sub("^ *", "", str)
    sub(" *$", "", str)
    return str
}

function dashes(len) {
    if (len) return "=" substr(DASHES, 1, len)
}

function split_pinfo(line,  c, i) {
    c=1
    for (i=1; i<=nfields; i++) {
        if (widths[i]) pinfo[fields[i]] = strip(substr(line, c, widths[i]))
        else pinfo[fields[i]] = strip(substr(line, c))
        c += widths[i] + 1
    }
}

function get_psinfo() {
    # parse unix ps command
    sfields=fpid ",ppid," fuser "," fcomm ","
    swidths="30,30,30,30,"
    nxfields = 1
    if (xfields) nxfields = split(xfields, fields, ",")
    else         xfields = fstime
    for (i=1; i<=nxfields; i++) swidths = swidths "50,"
    sfields = sfields xfields ",args"
    split(swidths, widths, ",")
    nfields = split(sfields, fields, ",")
    for (i=1; i<=nfields; i++)
        psopt = psopt " -o " fields[i] dashes(widths[i])
    out = runcmd("ps " psopt)
    split(out, ps_out, "\n")
    fields[1] = "pid"
    for (i in fields)
        ps_info[0,fields[i]] = " " fields[i]
    ps_info[0, "pid"] = 0
    ps_info[0, "ppid"] = -1
    children["-1"] = "0"
    delete ps_out[1]
    children[""]=""
    for (i in ps_out) {
        line = ps_out[i]
        split_pinfo(line)
        pid = pinfo["pid"]
        if (pinfo["ppid"] == pid)
            pinfo["ppid"] = "-1"
        ppid = pinfo["ppid"]
        if (pid == mypid || ppid == mypid)
            continue
        children[ppid] = append(children[ppid], pid)
        pinfo[fields[3]] = "(" pinfo[fields[3]] ")"
        sub(".*/", "", pinfo[fields[4]])
        pinfo[fields[4]] = "[" pinfo[fields[4]] "]"
        for (j in fields)
            ps_info[pid,fields[j]] = pinfo[fields[j]]
    }
}

function append(str, element) {
   if (str=="")
       return element
   if (match(","str",",","element","))
       return str
   return str "," element
}

function joinkeys(array, separator,   i,j,s) {
    for (i in array) {
        j = j s i
        s = separator
    }
    return j
}

function get_parents() {
    # get parents list of pids
    for (pid in all_pids) {
        if (!((pid,"ppid") in ps_info))
            continue
        while ((pid,"ppid") in ps_info) {
            ppid = ps_info[pid,"ppid"]
            pids_tree[ppid] = append(pids_tree[ppid], pid)
            last_ppid = pid
            pid = ppid
        }
        top_parents = append(top_parents, last_ppid)
    }
}

# recursive
function children2tree(pids) {
    # build children tree
    while (pids!="") {
        match(pids,",|$")
        pid = substr(pids,1,RSTART-1)
        pids = substr(pids,RSTART+1)
        if (pid in pids_tree)
            continue
        if (pid in children) {
            pids_tree[pid] = children[pid]
            children2tree(children[pid])
        }
    }
}

function build_tree() {
    #build process tree
    for(i in pids) s_pids = append(s_pids, pids[i])
    children2tree(s_pids)
    get_parents()
}

function print_proc(pid, pre, print_it, last) {
    # display process information with indent/tree/colors
    next_p = ""
    ppre = pre
    if (pid in all_pids) {
        print_it = 1
        ppre = selected substr(pre, 2) # ⇒ 🠖 🡆 ➤ ➥ ► ▶
    }
    if (print_it) {
        selected_pids[++nselpids] = pid
        if (pre == " ")  # head of hierarchy
            curr_p = next_p = " "
        else if (last) {  # last child
            curr_p = lastchild
            next_p = "  "
        } else { # not last child
            curr_p = child
            next_p = notchild
        }
        printf("%s%s", ppre, curr_p)
        for (i=1; i<=nfields; i++)
            if (fields[i] != "ppid")
                printf("%s ", colorize(fields[i], ps_info[pid,fields[i]]))
        printf("\n")
    }
    return next_p
}

# recursive
function _print_tree(pids, print_it, pre,     pid, next_p) {
    # display wonderful process tree
    while (pids!="") {
        match(pids,",|$")
        pid = substr(pids,1,RSTART-1)
        pids = substr(pids,RSTART+1)
        next_p = print_proc(pid, pre, print_it, (pids == ""))
        _print_tree(pids_tree[pid], (next_p != ""), pre next_p)
    }
}

function print_tree(child_only, sig, confirmed ) {
    # display full or children only process tree
    if (sig)
        kill_with_children(sig, confirmed)
    else
        _print_tree(top_parents, (! child_only), " ")
}

function kill_with_children(sig, False,  i) {
    # kill processes and children with signal
    _print_tree(top_parents, 0, " ")
    if (!nselpids) return
    printf("kill")
    for (i=nselpids;i>0;i--)
        printf(" %s", selected_pids[i])
    if (! confirmed) {
        answer = ask(" Confirm (y/[n]) ? ")
        if (answer != "y")
            return
    }
    for (i=nselpids;i>0;i--)
        system("kill -"sig" "selected_pids[i])
}

function split_hash_keys(str, hash,  t) {
    split(str, t)
    for (i in t) hash[t[i]] = 1
}

function main(argv) {
    # pgtree command line
    selected_pids[0]="";delete selected_pids[0]
    split_hash_keys(soptions, options)
    split(spids, pids)
    proctree(pids, ("-a" in options), (!("-C" in options)) )
    print_tree(("-c" in options), sig, ("-y" in options) )
}

BEGIN {
    DASHES="----------------------------------------------------"
    main()
}
EOF
)

pgt() {
    $awk -v mypid=$$ -v psopt="$PS_OPTION" -v fpid="$PGT_PID" -v fstime="$PGT_STIME" -v fcomm="$PGT_COMM" \
        -v fuser="$PGT_USER" -v spids="${pids[*]}" -v sig="$sig" -v xfields="$xfields" -v soptions="${options[*]}" \
        "$pgtreeawk" -- "$@"
}


_pgrep() {
    local opts=fxiwu: psfield="$PGT_COMM" icase exact=false

    while getopts "$opts" opt; do
        case $opt in
            f) psfield='args' ;;
            u) PS_OPTION=" -u $OPTARG" ;;
            i) icase=1 ;;
            x) exact=true ;;
        esac
    done
    shift $((OPTIND - 1))
    re="$1"
    [ "$re" ] || re='.*'
    $exact && re="^$1$" || re="$1"
    printf -v w "%*s" 20 ''
    w=${w// /-}
    PS_OPTION+=" -o $PGT_PID="$w" -o $psfield"
    ps $PS_OPTION | $awk '
    NR==1 { next }
    { pid=substr($0,1,20); gsub(" ","",pid) }
    { info=substr($0,22); sub(" *$","",info) }
    info ~ re { print pid }
    ' re="$re" IGNORECASE="$icase"
}

argopt="WRThIckKfxvinoya1C:p:u:U:g:G:P:s:t:F:O:w:"
args="${*}"
pids=(0)
PGT_PID='pid'
PGT_USER='user'
pgrep_args=()
options=()
watch='false'
threads=
color='auto'
wrap='auto'
while getopts "$argopt" opt; do
    case $opt in
        h) usage;;
        I) PGT_USER='uid' ;;
        C) color="$OPTARG" ;;
        [cya]) options+=("-$opt") ;;
        W) watch=true ;;
        w) wrap="$OPTARG" ;;
        T) threads=1; PGT_PID='spid'; PS_OPTION+=' -T' ;;
        k) sig=15 ;;
        K) sig=9 ;;
        p) pids=( "$OPTARG" );popt=1 ;;
        O) xfields="$OPTARG" ;;
        1) pids=(1) ;;
        R) PGT_PGREP='_pgrep' ;;
        [fxvino]) pgrep_args+=("-$opt") ;;
        [uUgGPstF]) pgrep_args+=("-$opt" "$OPTARG") ;;
        *) pgrep_args+=("$opt") ;;
    esac
done
case "$color" in
    y|yes|always) ;;
    n|no|never) options+=("-C") ;;
    *) [ -t 1 ] || options+=("-C") ;;
esac
case "$wrap" in
    y|yes) dowrap=true ;;
    n|no) dowrap=false ;;
    *) [ -t 1 ] && dowrap=true || dowrap=false ;;
esac
shift $((OPTIND - 1)); unset OPTIND
pgrep_args+=("$@")
if [ "$threads" ] ;then
    if [ "$popt" ];then
        pids=( $(ps -T -p "${pids[@]}" -o spid=) )
    else
        [ "$pgrep_args" ] && pids=( $($PGT_PGREP -w "${pgrep_args[@]}") )
    fi
else
    [ "$pgrep_args" ] && pids=( $($PGT_PGREP "${pgrep_args[@]}") )
fi
$dowrap && printf "\x1b[?7l"  # rmam
pgt
while $watch; do
    sleep 2
    clear
    echo "$(date): Watching : pgtree $args"
    pgt
done
$dowrap && printf "\x1b[?7h"  # smam
